### PR TITLE
RSDK-7759: Add SetRPM to st motor

### PR DESCRIPTION
**Pull request by martha-johnston**

### CODE REVIEW

**Review by randhid — CHANGES_REQUESTED** [review]
Remember to bump rdk as well.

**Comment by randhid** [comment]
@thegreatco

**Comment by martha-johnston** [comment]
hardware tests done, added a little bit more info to `README` where I was confused when trying to set this up

**Review by randhid — APPROVED** [review]

**Comment by martha-johnston** [comment]
@penguinland @thegreatco lmk if you have any thoughts, otherwise I'll merge later today

**Pull request merged**
